[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons,/mnt/openg2p-addons/openg2p-registry,/mnt/openg2p-addons/openg2p-program,/mnt/openg2p-addons/oca-queue
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$sRYi5JxzzpnzvhcCoLS2Vg$OiVJSwFIwOX.Zs3q7OSIJ/ojcDgEEuA8YMlaiOqkKyXo7HdgPlgWRrRm6PVdt8EkRQJ3U4ezliCGq6WLDfFBlw

