from providers.base import AIProvider


class MockProvider(AIProvider):

    async def summarize_damage(self, notes: str, damage_level: str, name: str, district: str, family_size: int) -> str:
        return (
            f"Household headed by {name} in {district} district suffered {damage_level} damage. "
            f"Family of {family_size} members affected. "
            f"Recommended priority for relief assistance."
        )

    async def generate_citizen_message(self, name: str, ref: str, status: str, next_step: str) -> str:
        return (
            f"Dear {name}, your relief application (Ref: {ref}) is now {status}. "
            f"Next step: {next_step}. - Govt Disaster Relief Unit"
        )

    async def generate_disaster_report(self, stats: dict) -> str:
        regions = ", ".join(stats.get("regions", ["Unknown"]))
        return (
            f"OFFICIAL DISASTER BRIEFING\n"
            f"---------------------\n"
            f"Total affected population: {stats.get('total_affected', 'N/A')}\n"
            f"Reported casualties: {stats.get('casualties', 'N/A')}\n"
            f"Structural damage: {stats.get('damaged_buildings', 'N/A')} buildings\n"
            f"Regions impacted: {regions}\n"
            f"Estimated economic loss: ${stats.get('economic_loss', 'N/A')}\n"
            f"---------------------\n"
            f"This report has been auto-generated by the GovRecover360 AI system. "
            f"All figures are subject to verification by field officers."
        )

    async def auditor_summary(self, logs: list, count: int) -> str:
        return (
            f"Audit summary: {count} actions reviewed. "
            f"No suspicious activity detected."
        )
